name: "Pull Request Build"

on:
  pull_request:
#    branches: [ main ]

jobs:
  linux-build-jvm:
    name: PR with jdk ${{matrix.java.version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '11', opts: '' },
          { 'version': '16', 'opts': '' },
          { 'version': '17', 'opts': '' }
        ]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'maven'
      - name: Test
        run: ./mvnw verify
